DBMS-Assignment-2
sharma-mohit-eca/GET2018 pull request #19
Opened 2018-08-16 18:09 UTC by metamohitsharma

Assignment 1:
Write SQL scripts for the following:
Create all tables of eCommerce Application: StoreFront covered in Session 1 Assignments. (Write all CREATE commands in a SQL file and run that SQL File).
Write a command to display all the table names present in StoreFront.
Write a command to remove Product table of the StoreFront database.
Create the Product table again.

Assignment 2:
Write SQL scripts for the following:
Insert sample data in StoreFront tables by using SQL files.
Display Id, Title, Category Title, Price of the products which are Active and recently added products should be at top.
Display the list of products which don't have any images.
Display all Id, Title and Parent Category Title for all the Categories listed, sorted by Parent Category Title and then Category Title. (If Category is top category then Parent Category Title column should display “Top Category” as value.)
Display Id, Title, Parent Category Title of all the leaf Categories (categories which are not parent of any other category)
Display Product Title, Price & Description which falls into particular category Title (i.e. “Mobile”)
Display the list of Products whose Quantity on hand (Inventory) is under 50.
Increase the Inventory of all the products by 100.

 
Assignment 3:
Write SQL scripts for the following:
Display Recent 50 Orders placed (Id, Order Date, Order Total).
Display 10 most expensive Orders.
Display all the Orders which are placed more than 10 days old and one or more items from those orders are still not shipped.
Display list of shoppers which haven't ordered anything since last month.
Display list of shopper along with orders placed by them in last 15 days. 
Display list of order items which are in “shipped” state for particular Order Id (i.e.: 1020))
Display list of order items along with order placed date which fall between Rs 20 to Rs 50 price.
Update first 20 Order items status to “Shipped” which are placed today.

2018-08-17 09:24 UTC, nehajain9302 requested changes
Please add output of table either in text form (from command terminal) or image form.

2018-08-20 07:23 UTC, nehajain9302 commented on DBMS/DBMSSession2/Question-2.sql
> +#Display Id, Title, Category Title, Price of the products which are Active and recently added products should be at top.
Do we have any flag for active property ?

2018-08-21 05:17 UTC, metamohitsharma commented on DBMS/DBMSSession2/Question-2.sql
> +#Display Id, Title, Category Title, Price of the products which are Active and recently added products should be at top.
Ma'am I have considered a Product as Active if its Quantity is more than Zero otherwise InActive.

2018-08-21 05:19 UTC, nehajain9302 approved these changes

2018-08-21 05:19 UTC, merged